<!DOCTYPE html>
<html>
  <?php
    include "common.php";
    echo generateHeader("intro");
  ?>

    <div id="content">
      <h3>The Introduction</h3>
      <p>Having decided on your narrative, you need to write the first part of your paper. The introduction, also called "background" by some journals. The background does exactly what it says on the tin. It communicates all the background knowledge required by the reader in order to understand what's coming in the rest of the paper. Great. But what does that actually mean?</p>
      <p>Okay, fair question. My favourite analogy here is <i>Star Wars</i> - and not that late 90s/early 2000s slop written by a man who did all his best work two or more decades prior. I'm talking 1977 here. The original. If you haven't seen it, then you totally should. Also, spoiler alert. ;)</p>
      <p>The introduction of a scientific paper represents the beginning or act one of the story. In the beginning of <i>Star Wars</i>, the viewer is not thrown into the thick of space battles between awkward-looking guys in plastic armour and bad '70s moustaches. That would be meaningless to them.</p>
      <p>In order for a battle scene to make any sense and hold any weight with the audience, we need to be told about who is fighting it and why. So instead, <i>Star Wars</i> starts off by showing us the main characters. We see Darth Vader boarding a ship and being a total bad-ass, chucking extras around and generally acting intimidating. He and his cronies later blow up an entire planet full of completely innocent people just to make a point. So we know he's definitely a Bad Guy.</p>
      <div class="figure">
        <img src="img/vaderInterrogates.jpg" alt="Darth Vader 'interrogates' rebel soldiers by strangulation" class="starWars">
        <p class="legend">Scenes like these, which feature wanton violence, are often used to introduce the Bad Guys in films. Their lack of restraint or reason invites the audience to immediately dislike them. Credit: 20th Century Fox/Lucasfilm.</p>
      </div>
      <p>We are then introduced to the droids as they take a message from the desperate princess and escape to a strange desert planet. After they are captured and sold, we are introduced to Luke Skywalker and his family. In this film, Luke is the audience's focal point; he's someone we can relate to. In a crazy universe full of weird looking aliens, lasers and strange lands, he's the one we can sympathise with and understand. So we see the story through his eyes.</p>
      <p>Over the next few scenes, he tells us about his hopes and dreams for a meaningful life beyond farming in a desert backwater (hmmm, contradiction in terms...? ;) ). He meets Obi-Wan Kenobi and we find out about his past as well as why the Empire needs to be destroyed. Once he loses his aunt and uncle (his only ties to his home), to the cruelty of the Empire, he has an impetus to go on a mission with Obi-Wan. This is essentially the end of <i>Star Wars'</i> introduction. We have the setting, we know who's fighting who and why, and all the major plot-driving characters have been introduced.</p>
      <p>All of this is accomplished in the first half hour to forty-five minutes of the film and it sets the stage for the battles to come. Now that we have the knowledge of this universe and what's going on, we can appreciate the obstacles that are later thrown up against the heroes and why they fight so hard to overcome them. Lightsaber duals are exciting not just because two guys are whaling on each other with flashy laser swords, but because the fight itself represents a clash between characters and ideologies in which we are emotionally invested.</p>
      <hr>
      <p>The introduction of a scientific paper is no different. You need to introduce the setting and the main characters and give enough background information about them so that the reader will be able to follow the plot later on when you start to talk about what experiments you did. So how do you do that? Well, if you've settled on a narrative and you know what experiments you're going to present in the results section, what background information is needed should start to come together fairly easily. Still, there are a few pointers worth noting.</p>
      <p>Most papers start with a very broad viewpoint and then narrow it down to specifics as they go. <i>Star Wars</i> does this too. The opening scene after the Wall-o-Text has two ships - one fairly small, and one absolutely massive with the appearance of being indestructible - flying along shooting at each other. The massive ship is chasing the smaller one and it's winning. So right away the audience knows there is conflict here and one side is way more powerful than the other. But that's all we know until the film starts to show us more specific details about who's doing the fighting and why.</p>
      <div class="figure">
        <img src="img/SWopening.jpg" alt="The opening scene from Star Wars with the Star Destroyer firing upon the smaller, outclassed vessel" class="starWars">
        <p class="legend">A master class in visual story-telling, this picture says it all. The huge all-powerful Star Destroyer effortlessly overtakes and captures the completely-outclassed rebel vessel in the opening scene of <i>Star Wars.</i> Credit: 20th Century Fox/Lucasfilm.</p>
      </div>
      <p>This introductory illustration of conflict in the film also gives us an idea as to the reason we're here watching the story. There's obviously a fight on and we're all invited to watch it go down. Similarly, in scientific writing, at around the broad overview beginning of the introduction, you'll often get some kind of reason for why this particular thing is being studied.</p>
      <p>For example, in bacteriology, authors will begin with a very basic description of what the organism under study is, and follow that up with all the horrible things it does to people. The implication is that it's a dangerous little bug that causes a lot of problems for people, so we are studying it to try and figure out how to prevent that. This is the anchor point of the narrative. The authors have started out by telling you <i>why</i> they are studying this thing and that it's not for the fun of it. This thing is dangerous and important and you should listen up!</p>
      <p>By giving the audience the reason to report these studies at the very first opportunity, the authors have achieved two things. Firstly, they've just handed us a lense through which to interpret their results. As we read the paper, we have in the back of our minds why these tests were necessary, which (just like in <i>Star Wars</i>) instantly makes us more involved in wanting to know the outcome. Secondly, they are essentially marketing their paper at the audience. They want to get us involved, not just to read the paper, but to cite it in our own research. The communication of their results to as many people as possible is important; they want to get their message out there. You should be doing the same.</P>
      <div class="figure">
        <a class="figure_link" href="img/intro01.png" target="_blank"><img src="img/intro01.png" alt="The first two sentences of a real-world paper"></a>
        <p class="legend">This figure is a snippet of the first two sentences from the introduction of a scientific paper on bacteriology. Don't worry if you don't know anything about bacteriology, we are going to ignore the technical jargon. In fact, I've highlighted the jargon in light blue so you know what to ignore. What's important here is the way they are communicating. The first sentence says "this is what we are working on" (that's the <i>Staphylococcus aureus</i> part. It's a nasty bug, you may have heard it called "golden staph" or "MRSA"). The sentence then continues with "these are the awful things it does". So right off the bat, they've started from a very broad overview: what it is and why it's important. The second sentence then starts to narrow down by talking about where it lives in humans (that's the topic of the paper). Now that we know this, we can throw out the scientific jargon and re-use this structure to write a paper about anything we like. For example: "Lions are large predators and are capable of killing humans. Most lions live on the African Savannah." (<a href="http://journals.plos.org/plospathogens/article?id=10.1371/journal.ppat.1002104" target="_blank">Pynnonen <i>et al.</i>, 2011</a>)</p>
      </div>
      <p>Once you've got your broad overview down, you then need to narrow it down very quickly into what you actually want to talk about. It's difficult to give any definitive advice here, as obviously each topic will be different. However, there are guidelines. You should constantly be asking yourself if what you're writing is relevant. Relevance here is "necessary background information". First key word: necessary. Scientists, like most of humanity I suspect, are lazy and really can't be bothered reading and writing any more than they really have to - they'd rather be in the lab. Therefore, your writing should be concise and to the point. Don't embellish and don't repeat yourself.</p>
      <div class="figure">
        <a class="figure_link" href="img/intro02.png" target="_blank"><img src="img/intro02.png" alt="First half paragraph of introduction of a real-world paper."></a>
        <p class="legend">The next few lines of this bacteriology paper illustrate this point perfectly. Again, the ignorable jargon is highlighted in blue so you can more easily follow the sentence structure. After the brief broad overview in the first two sentences, the author launches straight into relevant background information. Since the paper is all about how the bug lives in humans, they focus immediately on what they already know about where it resides. Their sentences are short and to the point, simply stating facts and backing them up with relevant citations. The sentence highlighted in yellow represents part of the basis of their hypothesis. You often find these statements of unknowns within the introduction. Collected together, these sentences neatly summarise what it is they're studying; what aspect of its behaviour they're studying (where it lives or "colonizes" as they put it); what they know about where it lives; what they don't know about it; and, finally, why studying this aspect of behaviour is important (it's a risk factor for [infectious disease jargon]). (<a href="http://journals.plos.org/plospathogens/article?id=10.1371/journal.ppat.1002104" target="_blank">Pynnonen <i>et al.</i>, 2011</a>)</p>
      </div>
      <p>The other key words are "background information". Again, if what you're writing cannot be described as background information, then it shouldn't be in the introduction. This is especially true of discussing results - that's for the discussion. By including any material that should not be in the introduction, you're pre-empting the results and conclusion and spoiling the ending. Imagine if Obi Wan gave away the plot point about the destruction of the Death Star in the middle of the Cantina scene where we meet Han Solo. What a waste of a great reveal in the beginning of the film before the audience even knows what the Death Star is!</p>
      <p>Finally, your introduction should include your hypothesis. After giving us all the necessary background on the characters and setting, <i>Star Wars</i> then tells us - through Obi Wan - that it's really imperative that the Empire be destroyed. As we watch the rest of the film, we the audience then have this in the back of our minds as the reason for following these events, and we want to see it happen. You'll find a similar construct towards the end of the introduction in any well-written scientific paper. The main "characters" and themes of the paper have been introduced and now the authors tell you what they're planning to do with them. This leads smoothly into the aims section of the paper...</p>
    </div>
    <?php
      echo generateFooter("intro");
     ?>
  </body>
</html>
